version: '3'
services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src/default.conf:/etc/nginx/conf.d/default.conf
      - ./lib:/var/www/html
    links:
      - fpm
#    depends_on:
#      - mysql
#      - fpm
  fpm:
    image: php:7-fpm
    container_name: php
    volumes:
      - ./src/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./lib:/var/www/html
#    links:
#      - mysql
#    depends_on:
#      - mysql
#  mysql:
#    image: mysql
#    container_name: mysql
#    restart: always
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=db
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=test123
